### PR TITLE
Added Binary Ninja disassembler backend

### PR DESCRIPTION
**Pull request by adrianherrera**
Last disassembler backend, I swear!! I just really like [Binary Ninja](https://binary.ninja), and I don't really have access to IDA anymore.

### CODE REVIEW

**Comment by vitalych** [comment]
I think it would make sense at this point to add protobuf-based cfg support to s2e, to abstract away various disassembly engines. Each engine produces a protobuf cfg consumed by various s2e plugins. Otherwise, each plugin would have to support N disassemblers.

**Comment by adrianherrera** [comment]
Sorry, I don't understand. This has nothing to do with S2E plugins. This is so that I can use s2e-env to generate and view basic block coverage in Binary Ninja.

**Comment by vitalych** [comment]
I meant that we should get output of all 3rd party tools in a generic format (e.g., protobuf), so that s2e-env (and s2e) can easily interface with them. Right now if you need coverage from IDA and Binary Ninja, you would write 2 different modules that do the same thing. Instead, if IDA and Binary Ninja generated protobuf format, you would write your coverage tool only once.

Unless what you have in mind is a Binary Ninja plugin that would display coverage directly in Binary Ninja iteself, in which case my remark is irrelevant.

**Comment by adrianherrera** [comment]
We already have a generic format, it's the translation block trace in JSON format produced by S2E. Each third party tool still needs to convert this translation block JSON into basic blocks based on how its disassembly engine and then render this information graphically.

I'm not sure what adding protobuf gives on top of the translation block JSON.

**Pull request merged**
